name: Docker-Build-MP

on: workflow_dispatch
    
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # logout: false
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      id: pushtodocker
      env:
        COMMIT_SHA: ${GITHUB_SHA}
      with:
        push: true
        repository: xero32/qec-mp
        tags: ${{ steps.pushtodocker.env.COMMIT_SHA }}
    - name: Prepare Singularity Environment
      uses: eWaterCycle/setup-singularity@v6
      with:
          singularity-version: 3.7.1
    - name: Convert to Singularity Image
      run: singularity build qec-mp_${GITHUB_REF##*/}.sif docker://xero32/qec-mp:${GITHUB_REF##*/}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: qec-mp_${GITHUB_REF##*/}.sif
        path: qec-mp_${GITHUB_REF##*/}.sif
        retention-days: 1
