name: Unittest

on: 
  push:
    branches:
      - '**'
      
jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        python setup.py develop
    - name: Pytest
      run: |
        export CONFIG_ENV_SIZE=5;
        export CONFIG_ENV_STACK_DEPTH=8;
        python -m pytest --cov-report=annotate --cov=src;
    - name: Testrun
      run: |
        export CONFIG_ENV_SIZE=5;
        export CONFIG_ENV_STACK_DEPTH=8;
        export CONFIG_LEARNER_MODEL_NAME=dummy_agent;
        export CONFIG_LEARNER_MODEL_CONFIG_FILE=dummy_agent.json
        export CONFIG_LEARNER_MODEL_CONFIG_LOCATION=src/config/model_spec/
        export CONFIG_LEARNER_MAX_TIME_H=0
        export CONFIG_LEARNER_MAX_TIME_MIN=3
        export CONFIG_LEARNER_DEVICE=cpu
        export CONFIG_ACTOR_NUM_CUDA=0
        export CONFIG_ACTOR_NUM_CPU=2
        export CONFIG_SUMMARY_PATH=gitruns
        export CONFIG_SUMMARY_DATE=gittest
        export CONFIG_LEARNER_SAVE_MODEL_PATH=gitnetworks
        mkdir gitnetworks
        mkdir gitruns
        mkdir gitruns/gittest
        python -m pytest --cov-report=annotate --cov=src;
      